Repository vmware/versatile-data-kit, pull requests merged in 2023-07, with the labels that each got.

#2342 vdk-control-cli: add vdk secrets command
  projects/vdk-control-cli/requirements.txt
  projects/vdk-control-cli/setup.cfg
  projects/vdk-control-cli/src/vdk/internal/control/command_groups/job/secrets.py
  projects/vdk-control-cli/src/vdk/internal/control/main.py
  projects/vdk-control-cli/src/vdk/internal/control/rest_lib/factory.py
  projects/vdk-control-cli/tests/vdk/internal/control/command_groups/job/test_secrets.py
Labels: cla-not-required

#2357 vdk-control-cli: add vdk secrets command
  projects/vdk-control-cli/src/vdk/internal/control/command_groups/job/properties.py
  projects/vdk-control-cli/src/vdk/internal/control/command_groups/job/secrets.py
Labels: cla-not-required

#2360 versatile-data-kit: remove gitlint pre-commit hook
  .gitlint
  .pre-commit-config.yaml
Labels: cla-not-required

#2348 control-service: split build job base image CI/CD step
  projects/control-service/cicd/.gitlab-ci.yml
  projects/control-service/projects/job-base-image-secure/Dockerfile-data-job-base
  projects/control-service/projects/job-base-image-secure/README.md
  projects/control-service/projects/job-base-image-secure/publish-job-base-image.sh
  projects/control-service/projects/job-base-image-secure/publish-job-base.sh
  projects/control-service/projects/python-image-secure/Dockerfile-python
  projects/control-service/projects/python-image-secure/README.md
  projects/control-service/projects/python-image-secure/publish-python-image.sh
Labels: cla-not-required

#2356 frontend: Fix navigation in Data Jobs
  projects/frontend/data-pipelines/gui/e2e/integration/explore/data-jobs/data-jobs.spec.js
  projects/frontend/data-pipelines/gui/e2e/integration/manage/data-jobs/data-jobs.spec.js
  projects/frontend/data-pipelines/gui/e2e/support/pages/base/data-pipelines/data-pipelines-base.po.js
  projects/frontend/data-pipelines/gui/projects/data-pipelines/src/lib/components/base-grid/data-jobs-base-grid.component.ts
  projects/frontend/data-pipelines/gui/projects/data-pipelines/src/lib/components/data-job/data-job-page.component.html
  projects/frontend/data-pipelines/gui/projects/data-pipelines/src/lib/components/data-jobs-explore/components/grid/data-jobs-explore-grid.component.html
  projects/frontend/data-pipelines/gui/projects/data-pipelines/src/lib/components/data-jobs-explore/components/grid/data-jobs-explore-grid.component.spec.ts
  projects/frontend/data-pipelines/gui/projects/data-pipelines/src/lib/components/data-jobs-manage/components/grid/data-jobs-manage-grid.component.html
  projects/frontend/data-pipelines/gui/projects/data-pipelines/src/lib/components/data-jobs-manage/components/grid/data-jobs-manage-grid.component.ts
  projects/frontend/data-pipelines/gui/projects/data-pipelines/src/lib/model/grid-config.model.ts
  projects/frontend/data-pipelines/gui/projects/data-pipelines/src/lib/shared/components/data-grid/column-filter/column-filter.component.ts
Labels: cla-not-required, area/frontend

#2362 vdk-impala: upgrade code to support pydantic 2.0
  projects/vdk-plugins/vdk-impala/src/vdk/plugin/impala/templates/load/dimension/scd1/00-dimension-scd1-definition.py
  projects/vdk-plugins/vdk-impala/src/vdk/plugin/impala/templates/load/fact/insert/00-fact-snapshot-definition.py
  projects/vdk-plugins/vdk-impala/src/vdk/plugin/impala/templates/load/fact/snapshot/00-fact-snapshot-definition.py
  projects/vdk-plugins/vdk-impala/src/vdk/plugin/impala/templates/load/versioned/00-versioned-definition.py
  projects/vdk-plugins/vdk-impala/tests/functional/template_regression_test.py
Labels: cla-not-required

#2358 frontend: bump toolchain versions in frontend build docker image
  projects/frontend/cicd/Dockerfile
  projects/frontend/cicd/version.txt
Labels: cla-not-required

#2344 control-service: add timestamps to helm chart
  projects/control-service/projects/helm_charts/pipelines-control-service/templates/deployment.yaml
Labels: cla-not-required

#2367 vdk-core: [Hot Fix] Stop throwing exceptions if config.ini not present
  projects/vdk-core/src/vdk/internal/builtin_plugins/config/job_config.py
  projects/vdk-core/tests/vdk/internal/builtin_plugins/config/test_job_config.py
Labels: cla-not-required

#2355 vdk-impala: Update README.md for vdk-impala
  projects/vdk-plugins/vdk-impala/README.md
Labels: cla-not-required

#2364 vdk-jupyter: Sample job notebook step
  projects/vdk-plugins/vdk-jupyter/vdk-jupyterlab-extension/vdk_jupyterlab_extension/jupyter_sample_job/10_notebook.ipynb
Labels: cla-not-required

#2351 vdk-smarter: introduce simple open ai plugin
  projects/vdk-plugins/vdk-smarter/.plugin-ci.yml
  projects/vdk-plugins/vdk-smarter/README.md
  projects/vdk-plugins/vdk-smarter/requirements.txt
  projects/vdk-plugins/vdk-smarter/setup.py
  projects/vdk-plugins/vdk-smarter/src/vdk/plugin/smarter/openai_plugin_entry.py
  projects/vdk-plugins/vdk-smarter/tests/jobs/sql-job/10_create_table.sql
  projects/vdk-plugins/vdk-smarter/tests/jobs/sql-job/20_populate_table.sql
  projects/vdk-plugins/vdk-smarter/tests/test_sql_review.py
Labels: cla-not-required

#2346 vdk-core: Allow different python versions for vdk docker images
  projects/vdk-core/cicd/Dockerfile-vdk-base
  projects/vdk-core/cicd/deploy-base-vdk-image.sh
Labels: cla-not-required

#2368 vdk-impala: support also pydantic 1.0
  projects/vdk-plugins/vdk-impala/requirements.txt
  projects/vdk-plugins/vdk-impala/src/vdk/plugin/impala/templates/load/versioned/00-versioned-definition.py
Labels: cla-not-required

#2370 control-service: logs endpoint doesn't hang
  projects/control-service/projects/pipelines_control_service/src/integration-test/java/com/vmware/taurus/datajobs/it/DataJobViewLogsIT.java
  projects/control-service/projects/pipelines_control_service/src/integration-test/resources/data_jobs/simple_job_read_logs.zip
  projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/KubernetesService.java
Labels: cla-not-required

#2374 control-service: better error logging for failed test
  projects/control-service/projects/pipelines_control_service/src/integration-test/java/com/vmware/taurus/datajobs/it/common/JobExecutionUtil.java
Labels: cla-not-required

#2359 frontend: quickstart-vdk operability tests using cypress
  projects/frontend/cicd/.gitlab-ci.yml
  projects/frontend/data-pipelines/gui/e2e/integration/frontend-tests/explore/data-jobs/data-jobs.spec.js
  projects/frontend/data-pipelines/gui/e2e/integration/frontend-tests/explore/data-jobs/details/data-job-details.spec.js
  projects/frontend/data-pipelines/gui/e2e/integration/frontend-tests/explore/data-jobs/executions/data-job-executions.spec.js
  projects/frontend/data-pipelines/gui/e2e/integration/frontend-tests/get-started/get-started-page-data-jobs-health-overview.spec.js
  projects/frontend/data-pipelines/gui/e2e/integration/frontend-tests/get-started/get-started-page.spec.js
  projects/frontend/data-pipelines/gui/e2e/integration/frontend-tests/manage/data-jobs/data-jobs.spec.js
  projects/frontend/data-pipelines/gui/e2e/integration/frontend-tests/manage/data-jobs/details/data-job-details.spec.js
  projects/frontend/data-pipelines/gui/e2e/integration/frontend-tests/manage/data-jobs/executions/data-job-executions.spec.js
  projects/frontend/data-pipelines/gui/e2e/integration/frontend-tests/router/router.spec.js
  projects/frontend/data-pipelines/gui/e2e/integration/quickstart-operability/quickstart.spec.js
  projects/frontend/data-pipelines/gui/e2e/support/pages/base/base-page.po.js
  projects/frontend/data-pipelines/gui/e2e/support/pages/base/data-pipelines/data-jobs-base.po.js
  projects/frontend/data-pipelines/gui/e2e/support/pages/base/data-pipelines/data-pipelines-base.po.js
  projects/frontend/data-pipelines/gui/e2e/support/pages/get-started/get-started-page.po.js
  projects/frontend/data-pipelines/gui/e2e/support/pages/manage/data-jobs/data-jobs.po.js
  projects/frontend/data-pipelines/gui/package.json
Labels: cla-not-required

#2361 vdk-jupyter: fix server error in jupyter ui and remove unneeded code
  projects/vdk-plugins/vdk-jupyter/vdk-jupyterlab-extension/src/serverRequests.ts
  projects/vdk-plugins/vdk-jupyter/vdk-jupyterlab-extension/vdk_jupyterlab_extension/handlers.py
  projects/vdk-plugins/vdk-jupyter/vdk-jupyterlab-extension/vdk_jupyterlab_extension/vdk_ui.py
Labels: cla-not-required, title needs formatting

#2375 frontend: Fix router event handling in base class
  projects/frontend/data-pipelines/gui/projects/data-pipelines/src/lib/components/base-grid/data-jobs-base-grid.component.ts
  projects/frontend/shared-components/gui/projects/shared/src/lib/core/navigation/services/navigation.service.ts
  projects/frontend/shared-components/gui/projects/shared/src/lib/core/system-events/event/models/event.codes.ts
  projects/frontend/shared-components/gui/projects/shared/src/lib/core/system-events/public-api.ts
  projects/frontend/shared-components/gui/projects/shared/src/lib/core/url-state-manager/url-state.manager.ts
Labels: cla-not-required, area/frontend

#2378 frontend: enable stable tagging
  projects/frontend/cicd/.gitlab-ci.yml
Labels: cla-not-required

#2386 frontend: remove e2e tests restrictions
  projects/frontend/cicd/.gitlab-ci.yml
Labels: cla-not-required

#2380 vdk-server: url in swagger ui is correct
  projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/datajobs/SwaggerConfiguration.java
  projects/control-service/projects/pipelines_control_service/src/main/resources/application-prod.properties
  projects/vdk-plugins/vdk-server/src/vdk/plugin/server/installer.py
Labels: cla-not-required

#2389 frontend: fix data-pipelines build scripts
  projects/frontend/cicd/.gitlab-ci.yml
  projects/frontend/cicd/install_data_pipelines.sh
Labels: cla-not-required

#2376 vdk-core: Set sender when checking if email exists
  projects/vdk-core/src/vdk/internal/builtin_plugins/notification/notification_base.py
Labels: cla-not-required

#2381 control-service: push to multiple registries
  .gitlab-ci.yml
  cicd/.gitlab-ci-lib.yml
  cicd/docker_parse.sh
  cicd/docker_push_vdk.sh
  projects/control-service/cicd/.gitlab-ci.yml
  projects/control-service/projects/job-base-image-secure/publish-job-base-image.sh
  projects/control-service/projects/job-base-image/publish-job-base.sh
Labels: cla-not-required

#2387 vdk-plugin-control-cli: add secrets command
  projects/vdk-plugins/vdk-plugin-control-cli/src/vdk/plugin/control_cli_plugin/control_service_secrets_client.py
  projects/vdk-plugins/vdk-plugin-control-cli/src/vdk/plugin/control_cli_plugin/secrets_plugin.py
  projects/vdk-plugins/vdk-plugin-control-cli/src/vdk/plugin/control_cli_plugin/vdk_plugin_control_cli.py
  projects/vdk-plugins/vdk-plugin-control-cli/tests/jobs/secrets-job/10_secrets_step.py
  projects/vdk-plugins/vdk-plugin-control-cli/tests/jobs/secrets-job/config.ini
  projects/vdk-plugins/vdk-plugin-control-cli/tests/test_secrets_plugin.py
Labels: cla-not-required

#2369 vdk-impala: Truncate table before inserting data
  projects/vdk-plugins/vdk-impala/src/vdk/plugin/impala/templates/load/fact/insert/02-handle-quality-checks.py
  projects/vdk-plugins/vdk-impala/tests/functional/template_regression_test.py
Labels: cla-not-required

#2326 control-service: add helm template for alertmanager
  projects/control-service/projects/helm_charts/pipelines-control-service/templates/alertmanager.yaml
  projects/control-service/projects/helm_charts/pipelines-control-service/templates/secret_alertmanager.yaml
  projects/control-service/projects/helm_charts/pipelines-control-service/values.yaml
Labels: cla-not-required

#2409 vdk-control-cli: remove set-secret for properties
  examples/online-exhibition/README.md
  projects/vdk-control-cli/src/vdk/internal/control/command_groups/job/properties.py
  projects/vdk-control-cli/tests/vdk/internal/control/command_groups/job/test_properties.py
Labels: cla-not-required

#2407 vdk-jupyter: publish image to pip registry
  projects/vdk-plugins/vdk-jupyter/.plugin-ci.yml
  projects/vdk-plugins/vdk-jupyter/vdk-jupyterlab-extension/README.md
  projects/vdk-plugins/vdk-jupyter/vdk-jupyterlab-extension/pyproject.toml
  projects/vdk-plugins/vdk-jupyter/vdk-jupyterlab-extension/setup.py
Labels: cla-not-required

#2388 control-service: remove unused dependency influxdb
  projects/control-service/projects/base/build.gradle
  projects/control-service/projects/base/src/test/resources/application.properties
  projects/control-service/projects/helm_charts/pipelines-control-service/example-vdk-options.ini
  projects/control-service/projects/pipelines_control_service/src/test/java/com/vmware/taurus/service/deploy/VdkOptionsReaderTest.java
  projects/control-service/projects/pipelines_control_service/src/test/resources/vdk_options/test_vdk_options.ini
  projects/control-service/projects/versions-of-external-dependencies.gradle
Labels: cla-not-required

#2411 control-service: add configurable smtp host property
  projects/control-service/projects/helm_charts/pipelines-control-service/templates/deployment.yaml
  projects/control-service/projects/helm_charts/pipelines-control-service/values.yaml
  projects/control-service/projects/pipelines_control_service/src/main/resources/application.properties
Labels: cla-not-required

#2414 vdk-jupyter: Add a message describing how to contact the Jupyter devs
  projects/vdk-plugins/vdk-jupyter/vdk-jupyterlab-extension/README.md
Labels: cla-not-required

#2390 frontend: push docker images to both repos
  projects/frontend/cicd/.gitlab-ci.yml
  projects/frontend/cicd/publish_image_docker.sh
Labels: cla-not-required

#2418 control-service: Add helm chart entries for Vault Configuation
  projects/control-service/projects/helm_charts/pipelines-control-service/templates/_helpers.tpl
  projects/control-service/projects/helm_charts/pipelines-control-service/templates/deployment.yaml
  projects/control-service/projects/helm_charts/pipelines-control-service/templates/secret_vault.yaml
  projects/control-service/projects/helm_charts/pipelines-control-service/values.yaml
Labels: cla-not-required

#2416 vdk-plugins: include Ingestion hooks documentation
  projects/vdk-plugins/README.md
Labels: cla-not-required

#2338 support: slack notification on pipeline failure
  .gitlab-ci.yml
  cicd/notify.sh
Labels: cla-not-required

#2428 vdk-jupyter: remove delete operation
  projects/vdk-plugins/vdk-jupyter/vdk-jupyterlab-extension/schema/plugin.json
  projects/vdk-plugins/vdk-jupyter/vdk-jupyterlab-extension/src/__tests__/delete-job-component.spec.ts
  projects/vdk-plugins/vdk-jupyter/vdk-jupyterlab-extension/src/__tests__/show-dialog.spec.tsx
  projects/vdk-plugins/vdk-jupyter/vdk-jupyterlab-extension/src/commandsAndMenu.tsx
  projects/vdk-plugins/vdk-jupyter/vdk-jupyterlab-extension/src/components/DeleteJob.tsx
  projects/vdk-plugins/vdk-jupyter/vdk-jupyterlab-extension/ui-tests/tests/vdk-jupyterlab-extension.spec.ts
  projects/vdk-plugins/vdk-jupyter/vdk-jupyterlab-extension/vdk_jupyterlab_extension/handlers.py
  projects/vdk-plugins/vdk-jupyter/vdk-jupyterlab-extension/vdk_jupyterlab_extension/vdk_ui.py
Labels: cla-not-required

#2417 control-service: set Execution and JobQuery APIs to stable
  projects/control-service/projects/model/apidefs/datajob-api/api.yaml
Labels: cla-not-required

#2435 control-service: switch to Approle Vault authentication
  projects/control-service/projects/helm_charts/pipelines-control-service/templates/_helpers.tpl
  projects/control-service/projects/helm_charts/pipelines-control-service/templates/deployment.yaml
  projects/control-service/projects/helm_charts/pipelines-control-service/values.yaml
  projects/control-service/projects/pipelines_control_service/src/integration-test/java/com/vmware/taurus/secrets/service/vault/TestVaultJobSecretsServiceIT.java
  projects/control-service/projects/pipelines_control_service/src/integration-test/java/com/vmware/taurus/secrets/service/vault/VaultTestSetup.java
  projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/secrets/service/vault/VaultConfiguration.java
  projects/control-service/projects/pipelines_control_service/src/main/resources/application.properties
  specs/vep-1493-vault-integration/README.md
Labels: cla-not-required

#2432 versatile-data-kit: clarify structure of VDK repo
  CONTRIBUTING.md
Labels: cla-not-required

#2352 vdk-jupyter: Create init cell when opening new notebook
  projects/vdk-plugins/vdk-jupyter/vdk-jupyterlab-extension/src/index.ts
  projects/vdk-plugins/vdk-jupyter/vdk-jupyterlab-extension/src/initVDKConfigCell.ts
  projects/vdk-plugins/vdk-jupyter/vdk-jupyterlab-extension/ui-tests/tests/vdk-jupyterlab-extension.spec.ts
Labels: cla-not-required

#2413 control-service: release job builder in 2 repos
  cicd/docker_push_vdk.sh
  projects/control-service/cicd/.gitlab-ci.yml
  projects/control-service/projects/job-builder-secure/publish-vdk-job-builder-secure.sh
  projects/control-service/projects/job-builder-secure/version.txt
  projects/control-service/projects/job-builder/publish-vdk-job-builder.sh
  projects/control-service/projects/job-builder/version.txt
Labels: cla-not-required

#2429 control-service: job-builder using kaniko fix
  projects/control-service/projects/job-builder/Dockerfile
  projects/control-service/projects/job-builder/README.md
  projects/control-service/projects/job-builder/build_image.sh
  projects/control-service/projects/job-builder/version.txt
  projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/exception/ExternalSystemError.java
  projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/deploy/DeploymentNotificationHelper.java
  projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/deploy/DockerImageName.java
  projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/deploy/EcrRegistryInterface.java
  projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/deploy/JobImageBuilder.java
  projects/control-service/projects/pipelines_control_service/src/test/java/com/vmware/taurus/service/deploy/DockerImageNameTest.java
  projects/control-service/projects/pipelines_control_service/src/test/java/com/vmware/taurus/service/deploy/EcrRegistryInterfaceTest.java
  projects/control-service/projects/pipelines_control_service/src/test/java/com/vmware/taurus/service/deploy/JobImageBuilderTest.java
Labels: cla-not-required

#2406 vdk-jupyter: convert job operation
  projects/vdk-plugins/vdk-jupyter/vdk-jupyterlab-extension/jest.config.js
  projects/vdk-plugins/vdk-jupyter/vdk-jupyterlab-extension/package-lock.json
  projects/vdk-plugins/vdk-jupyter/vdk-jupyterlab-extension/package.json
  projects/vdk-plugins/vdk-jupyter/vdk-jupyterlab-extension/src/__tests__/convert-job-to-notebook-component.spec.ts
  projects/vdk-plugins/vdk-jupyter/vdk-jupyterlab-extension/src/commandsAndMenu.tsx
  projects/vdk-plugins/vdk-jupyter/vdk-jupyterlab-extension/src/components/ConvertJobToNotebook.tsx
  projects/vdk-plugins/vdk-jupyter/vdk-jupyterlab-extension/src/components/props.tsx
  projects/vdk-plugins/vdk-jupyter/vdk-jupyterlab-extension/src/index.ts
  projects/vdk-plugins/vdk-jupyter/vdk-jupyterlab-extension/src/serverRequests.ts
  projects/vdk-plugins/vdk-jupyter/vdk-jupyterlab-extension/testutils/jest-file-mock.js
  projects/vdk-plugins/vdk-jupyter/vdk-jupyterlab-extension/testutils/jest-setup-files.js
  projects/vdk-plugins/vdk-jupyter/vdk-jupyterlab-extension/ui-tests/tests/convert-job.spec.ts
  projects/vdk-plugins/vdk-jupyter/vdk-jupyterlab-extension/ui-tests/tests/data/convert-test-job-dirty/10_drop_table.sql
  projects/vdk-plugins/vdk-jupyter/vdk-jupyterlab-extension/ui-tests/tests/data/convert-test-job-dirty/20_create_table.sql
  projects/vdk-plugins/vdk-jupyter/vdk-jupyterlab-extension/ui-tests/tests/data/convert-test-job-dirty/30_ingest_to_table.py
  projects/vdk-plugins/vdk-jupyter/vdk-jupyterlab-extension/ui-tests/tests/utils.ts
  projects/vdk-plugins/vdk-jupyter/vdk-jupyterlab-extension/ui-tests/tests/vdk-jupyterlab-extension.spec.ts
  projects/vdk-plugins/vdk-jupyter/vdk-jupyterlab-extension/vdk_jupyterlab_extension/convert_job.py
  projects/vdk-plugins/vdk-jupyter/vdk-jupyterlab-extension/vdk_jupyterlab_extension/handlers.py
  projects/vdk-plugins/vdk-jupyter/vdk-jupyterlab-extension/vdk_jupyterlab_extension/job_data.py
  projects/vdk-plugins/vdk-jupyter/vdk-jupyterlab-extension/vdk_jupyterlab_extension/tests/test_convert_job_directory_processor.py
  projects/vdk-plugins/vdk-jupyter/vdk-jupyterlab-extension/vdk_jupyterlab_extension/tests/test_directory_archiver.py
  projects/vdk-plugins/vdk-jupyter/vdk-jupyterlab-extension/vdk_jupyterlab_extension/vdk_ui.py
Labels: cla-not-required

#2447 control-service: job-builder-secure using kaniko fix
  projects/control-service/projects/job-builder-secure/Dockerfile
  projects/control-service/projects/job-builder-secure/README.md
  projects/control-service/projects/job-builder-secure/build_image.sh
  projects/control-service/projects/job-builder-secure/version.txt
Labels: cla-not-required

#2446 control-service: run integration tests on multiple namespace.
  projects/control-service/cicd/.gitlab-ci.yml
Labels: cla-not-required

#2295 control-service: use full url for heartbeat tests and heartbeat tests run in multiple namespaces
  projects/control-service/cicd/deploy-testing-pipelines-service.sh
  projects/control-service/cicd/post_deploy_test_heartbeat_config.ini
  projects/vdk-control-cli/cicd/release_test_heartbeat_config.ini
  projects/vdk-heartbeat/README.md
  projects/vdk-plugins/quickstart-vdk/cicd/release_acceptance_test_heartbeat_config.ini
Labels: cla-not-required

#2445 vdk-plugins: fix build of multiple plugins
  projects/vdk-plugins/.plugin-common.yml
  projects/vdk-plugins/build-plugin.sh
  projects/vdk-plugins/vdk-greenplum/.plugin-ci.yml
  projects/vdk-plugins/vdk-greenplum/requirements.txt
  projects/vdk-plugins/vdk-greenplum/setup.py
  projects/vdk-plugins/vdk-impala/.plugin-ci.yml
  projects/vdk-plugins/vdk-impala/requirements.txt
  projects/vdk-plugins/vdk-kerberos-auth/.plugin-ci.yml
  projects/vdk-plugins/vdk-kerberos-auth/requirements.txt
  projects/vdk-plugins/vdk-postgres/.plugin-ci.yml
  projects/vdk-plugins/vdk-postgres/requirements.txt
  projects/vdk-plugins/vdk-postgres/setup.py
  projects/vdk-plugins/vdk-trino/requirements.txt
Labels: cla-not-required

#2450 [bug fix] vdk-core: Add job name to state
  projects/vdk-core/src/vdk/internal/builtin_plugins/notification/notification.py
  projects/vdk-core/tests/functional/run/test_run_notifications.py
Labels: cla-not-required

#2470 control-service: prevent integer translation in helm chart
  projects/control-service/projects/helm_charts/pipelines-control-service/values.yaml
Labels: cla-not-required

#2472 control-service: install necessary dependencies to job builder secure
  projects/control-service/cicd/.gitlab-ci.yml
  projects/control-service/projects/job-base-image-secure/Dockerfile-data-job-base
  projects/control-service/projects/job-base-image-secure/publish-job-base-image.sh
  projects/control-service/projects/job-builder-secure/Dockerfile.python.vdk
Labels: cla-not-required

#2393 vdk-heartbeat: cover requirements.txt automatic installs
  projects/vdk-heartbeat/.gitlab-ci.yml
  projects/vdk-heartbeat/cicd/cicd_heartbeat_config.ini
  projects/vdk-heartbeat/src/vdk/internal/heartbeat/vdk_heartbeat_data_job/empty/10_do_nothing.py
  projects/vdk-heartbeat/src/vdk/internal/heartbeat/vdk_heartbeat_data_job/empty/requirements.txt
  projects/vdk-heartbeat/src/vdk/internal/heartbeat/vdk_heartbeat_data_job/impala/05_set_properties.py
  projects/vdk-heartbeat/src/vdk/internal/heartbeat/vdk_heartbeat_data_job/simple/10_simple.py
  projects/vdk-heartbeat/src/vdk/internal/heartbeat/vdk_heartbeat_data_job/simple/requirements.txt
  projects/vdk-heartbeat/src/vdk/internal/heartbeat/vdk_heartbeat_data_job/trino/05_set_properties.py
  projects/vdk-heartbeat/src/vdk/internal/heartbeat/vdk_heartbeat_data_job/trino/requirements.txt
Labels: cla-not-required

#2475 control-service: remove default vault token
  projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/secrets/service/vault/VaultConfiguration.java
  projects/control-service/projects/pipelines_control_service/src/main/resources/application.properties
Labels: cla-not-required

#2476 control-service: fix typo in helm chart read only root filesystem property
  projects/control-service/projects/helm_charts/pipelines-control-service/templates/deployment.yaml
Labels: cla-not-required

#2481 vdk-jupyter: pin word wrap package to newer version because of security issue
  projects/vdk-plugins/vdk-jupyter/vdk-jupyterlab-extension/package-lock.json
  projects/vdk-plugins/vdk-jupyter/vdk-jupyterlab-extension/package.json
Labels: cla-not-required

#2477 vdk-control-cli: pass the printer class in JobDeploy creation and add additional memory printer
  projects/vdk-control-cli/src/vdk/internal/control/command_groups/job/deploy_cli.py
  projects/vdk-control-cli/src/vdk/internal/control/command_groups/job/deploy_cli_impl.py
  projects/vdk-control-cli/src/vdk/internal/control/utils/output_printer.py
  projects/vdk-control-cli/tests/vdk/internal/control/utils/test_output_printer.py
Labels: cla-not-required

#2456 specs: VEP-2448: VDK Run Logs: Simplified And Readable
  specs/vep-2448-vdk-run-logs-simplified-and-readable/README.md
Labels: cla-not-required

#2486 frontend: Fix bug in Cypress plugin
  projects/frontend/data-pipelines/gui/e2e/plugins/helpers/job-helpers.plugins.js
Labels: cla-not-required, area/frontend

#2474 vdk-jupyter: vdk jupyter deploy job fix
  projects/vdk-plugins/vdk-jupyter/vdk-jupyterlab-extension/src/__tests__/deploy-job-component.spec.ts
  projects/vdk-plugins/vdk-jupyter/vdk-jupyterlab-extension/src/components/DeployJob.tsx
  projects/vdk-plugins/vdk-jupyter/vdk-jupyterlab-extension/src/jobData.ts
  projects/vdk-plugins/vdk-jupyter/vdk-jupyterlab-extension/src/vdkOptions/vdk_options.ts
  projects/vdk-plugins/vdk-jupyter/vdk-jupyterlab-extension/vdk_jupyterlab_extension/handlers.py
  projects/vdk-plugins/vdk-jupyter/vdk-jupyterlab-extension/vdk_jupyterlab_extension/vdk_options/vdk_options.py
  projects/vdk-plugins/vdk-jupyter/vdk-jupyterlab-extension/vdk_jupyterlab_extension/vdk_ui.py
Labels: cla-not-required

#2492 control-service: exclude pyc files from dj validation
  projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/upload/JobUploadValidator.java
Labels: cla-not-required

#2433 frontend: set favicon for vdk
  projects/frontend/data-pipelines/gui/projects/ui/src/favicon.ico
Labels: cla-not-required

#2490 control-service: ability to set builder image per python version
  projects/control-service/projects/helm_charts/pipelines-control-service/values.yaml
  projects/control-service/projects/pipelines_control_service/src/integration-test/java/com/vmware/taurus/datajobs/it/TestJobImageBuilderDynamicVdkImageIT.java
  projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/deploy/JobImageBuilder.java
  projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/deploy/SupportedPythonVersions.java
  projects/control-service/projects/pipelines_control_service/src/test/java/com/vmware/taurus/service/deploy/JobImageBuilderTest.java
  projects/control-service/projects/pipelines_control_service/src/test/java/com/vmware/taurus/service/deploy/SupportedPythonVersionsTest.java
Labels: cla-not-required

#2491 frontend: fix pushing images
  projects/frontend/cicd/.gitlab-ci.yml
Labels: cla-not-required

#2466 versatile-data-kit: remove global image from Gitlab CI
  .gitlab-ci.yml
  projects/vdk-control-cli/.gitlab-ci.yml
  projects/vdk-core/.gitlab-ci.yml
  projects/vdk-heartbeat/.gitlab-ci.yml
  projects/vdk-plugins/vdk-control-api-auth/.plugin-ci.yml
  projects/vdk-plugins/vdk-csv/.plugin-ci.yml
  projects/vdk-plugins/vdk-dag/.plugin-ci.yml
  projects/vdk-plugins/vdk-gdp-execution-id/.plugin-ci.yml
  projects/vdk-plugins/vdk-ingest-file/.plugin-ci.yml
  projects/vdk-plugins/vdk-ingest-http/.plugin-ci.yml
  projects/vdk-plugins/vdk-ipython/.plugin-ci.yml
  projects/vdk-plugins/vdk-jobs-troubleshooting/.plugin-ci.yml
  projects/vdk-plugins/vdk-lineage-model/.plugin-ci.yml
  projects/vdk-plugins/vdk-lineage/.plugin-ci.yml
  projects/vdk-plugins/vdk-logging-format/.plugin-ci.yml
  projects/vdk-plugins/vdk-meta-jobs/.plugin-ci.yml
  projects/vdk-plugins/vdk-notebook/.plugin-ci.yml
  projects/vdk-plugins/vdk-plugin-control-cli/.plugin-ci.yml
  projects/vdk-plugins/vdk-properties-fs/.plugin-ci.yml
  projects/vdk-plugins/vdk-server/.plugin-ci.yml
  projects/vdk-plugins/vdk-smarter/.plugin-ci.yml
  projects/vdk-plugins/vdk-snowflake/.plugin-ci.yml
  projects/vdk-plugins/vdk-sqlite/.plugin-ci.yml
  projects/vdk-plugins/vdk-test-utils/.plugin-ci.yml
  projects/vdk-plugins/vdk-trino/.plugin-ci.yml
Labels: cla-not-required

#2496 control-service: release job builder secure 1.3.0
  projects/control-service/projects/job-builder-secure/version.txt
Labels: cla-not-required

#2499 vdk-ipython: use package structure for file
  projects/vdk-plugins/vdk-ipython/README.md
  projects/vdk-plugins/vdk-ipython/setup.py
  projects/vdk-plugins/vdk-ipython/src/vdk/plugin/ipython.py
  projects/vdk-plugins/vdk-ipython/tests/test_plugin.py
  projects/vdk-plugins/vdk-jupyter/vdk-jupyterlab-extension/src/components/ConvertJobToNotebook.tsx
  projects/vdk-plugins/vdk-jupyter/vdk-jupyterlab-extension/src/initVDKConfigCell.ts
  projects/vdk-plugins/vdk-jupyter/vdk-jupyterlab-extension/ui-tests/tests/convert-job.spec.ts
  projects/vdk-plugins/vdk-jupyter/vdk-jupyterlab-extension/ui-tests/tests/vdk-jupyterlab-extension.spec.ts
  projects/vdk-plugins/vdk-jupyter/vdk-jupyterlab-extension/vdk_jupyterlab_extension/jupyter_sample_job/10_notebook.ipynb
Labels: cla-not-required

#2498 vdk-greenplum: adopt testcontainers
  projects/vdk-plugins/vdk-greenplum/requirements.txt
  projects/vdk-plugins/vdk-greenplum/tests/conftest.py
  projects/vdk-plugins/vdk-greenplum/tests/docker-compose.yml
Labels: cla-not-required
